import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import GContainer from '@/componemts/Share/GContainer'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import { Providers } from '@/componemts/Share/Provider'

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] })
const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'E-Commerce web',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <AntdRegistry>
                    <Providers>
                        <GContainer>{children}</GContainer>
                    </Providers>
                </AntdRegistry>
            </body>
        </html>
    )
}
